#!/bin/bash

ls –l myfile xfile anotherfile 2> errorcontent 1> correctcontent

# существующие файлы будут в коррект, а не существующие в ошибке (можно проверить файлы cat)

# МОЖНО и ошибки и успешный вывод перенаправить в один файл &>
