#!/bin/bash
exec 3>myfile
echo "This should display on the screen"
echo "and this should be stored in the file" >&3
echo "And this should be back on the screen"

# создание своего дискриптора (можно до 8) 3 из них стандартные 
